{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.nativelib",
    "module": "nativelib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.mashanshui",
          "module": "rhea-inhouse",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativelib-1.0.0.aar",
          "url": "nativelib-1.0.0.aar",
          "size": 889991,
          "sha512": "e902f8584ecdb65908c1653a90f83463939c341d055477f6bb3397c2098663bc47f867f5f1b2e23acd52cf8479eb5e9318811c476bd2da2f893e8802a109b947",
          "sha256": "6c27acb4efef535d47bb1ad7fa592c62004bb3ae66513b5bc780e97dcd55ea3c",
          "sha1": "d997479d546f4c6a3046714effb96b60007820cc",
          "md5": "8111b42d70bea54e59edf1b639c2d7fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.bytedance.android",
          "module": "shadowhook",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.kuaishou.koom",
          "module": "koom-java-leak",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "io.github.mashanshui",
          "module": "rhea-inhouse",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativelib-1.0.0.aar",
          "url": "nativelib-1.0.0.aar",
          "size": 889991,
          "sha512": "e902f8584ecdb65908c1653a90f83463939c341d055477f6bb3397c2098663bc47f867f5f1b2e23acd52cf8479eb5e9318811c476bd2da2f893e8802a109b947",
          "sha256": "6c27acb4efef535d47bb1ad7fa592c62004bb3ae66513b5bc780e97dcd55ea3c",
          "sha1": "d997479d546f4c6a3046714effb96b60007820cc",
          "md5": "8111b42d70bea54e59edf1b639c2d7fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nativelib-1.0.0-sources.jar",
          "url": "nativelib-1.0.0-sources.jar",
          "size": 117809,
          "sha512": "b1f7ee5ea00c55d810c57e32b567b59e724bb646c2daa285e0e2b9f1e6f51b4b886c4bb47a8273db90e1136b25632970ef0dbf1edc981d3a88a0ea256ca7d411",
          "sha256": "59cb52edc67ff1e5a3ae54485731529129dc79622f3e677d70b07b0feb306ad4",
          "sha1": "4532ec087047d587b55a431bf8f2ef0049f2c483",
          "md5": "99c4c82b880a9131f9e900217448f26d"
        }
      ]
    }
  ]
}
